[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9.0.0"

##############################################
# Рекомендуемые заголовки, чтобы чанки и статик
# отдавались корректно и кэшировались браузером
##############################################
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    content-type = "application/javascript"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"


