import type { TFunction } from 'i18next';
import type { IngredientCategoryOption } from '@/shared/lib/types/ingredients.types';

const INGREDIENT_CATEGORY_KEYS: Record<string, readonly string[]> = {
	salts: [
		'salt-rock',
		'salt-sea',
		'salt-kosher',
		'salt-iodized',
		'salt-himalayan',
		'salt-flakes',
		'salt-smoked',
	],
	'oils-fats': [
		'oil-olive',
		'oil-sunflower',
		'oil-vegetable',
		'oil-sesame',
		'oil-peanut',
		'oil-coconut',
		'oil-avocado',
		'oil-flaxseed',
		'fat-butter',
		'fat-ghee',
		'fat-lard',
		'fat-duck',
	],
	vegetables: [
		'veg-leafy',
		'veg-cruciferous',
		'veg-nightshade',
		'veg-allium',
		'veg-root',
		'veg-gourd',
		'veg-stem',
		'veg-legume',
		'veg-cabbage',
		'veg-peppers',
		'veg-tomato',
		'veg-cucumber',
	],
	fruits: [
		'fruit-citrus',
		'fruit-berries',
		'fruit-stone',
		'fruit-pome',
		'fruit-tropical',
		'fruit-melons',
		'fruit-dried',
	],
	mushrooms: ['mush-fresh', 'mush-dried', 'mush-cultivated', 'mush-forest'],
	herbs: ['greens', 'herbs-dried'],
	spices: [
		'spice-whole',
		'spice-ground',
		'spice-blends',
		'spice-chili',
		'spice-aromatic',
	],
	grains: [
		'grain-rice',
		'grain-wheat',
		'grain-oats',
		'grain-buckwheat',
		'grain-barley',
		'grain-millet',
		'grain-quinoa',
		'grain-corn',
	],
	'pasta-noodles': [
		'pasta-italian',
		'noodles-egg',
		'noodles-rice',
		'noodles-soba',
		'noodles-udon',
		'noodles-glass',
	],
	legumes: [
		'legume-beans',
		'legume-peas',
		'legume-lentils',
		'legume-soy',
		'legume-sprouts',
	],
	'nuts-seeds': ['nuts', 'seeds', 'nut-butters', 'tahini'],
	baking: ['flours', 'leavening', 'additives', 'chocolate'],
	sweeteners: ['sugar', 'honey', 'syrups', 'artificial'],
	'vinegars-acids': [
		'vinegar-apple',
		'vinegar-rice',
		'vinegar-wine',
		'vinegar-balsamic',
		'acid-citric',
	],
	'sauces-condiments': [
		'sauce-soy',
		'sauce-fish',
		'sauce-oyster',
		'sauce-teriyaki',
		'sauce-worcestershire',
		'sauce-ketchup',
		'sauce-mayo',
		'sauce-mustard',
		'sauce-tomato-paste',
		'sauce-chili-paste',
		'sauce-pesto',
		'sauce-tahini',
	],
	'dairy-eggs': [
		'milk-cream',
		'yogurt-kefir',
		'cheese',
		'dairy-butter',
		'eggs',
		'alt-milks',
	],
	meat: ['beef', 'pork', 'lamb', 'veal', 'game'],
	poultry: ['chicken', 'turkey', 'duck', 'other-poultry'],
	'fish-seafood': [
		'fish-white',
		'fish-fatty',
		'seafood',
		'canned-fish',
		'smoked-fish',
	],
	'broths-stocks': ['broth-cubes', 'broth-liquid', 'demiglace'],
	'canned-pickled': [
		'canned-veg',
		'canned-fruit',
		'pickles',
		'legume-canned',
		'sauces-jarred',
	],
	frozen: ['frozen-veg', 'frozen-fruit', 'frozen-seafood', 'frozen-dough'],
	bakery: ['bread', 'flatbreads', 'pastries', 'breadcrumbs'],
	'breakfast-cereals': ['cereals', 'porridge-mixes'],
	snacks: ['chips', 'dried-meat', 'bars'],
	beverages: ['tea-coffee', 'juices', 'sodas', 'water', 'non-dairy'],
	other: ['baby', 'diet', 'supplements'],
} as const;

export const getIngredientCategoryGroupsOptions = (
	t: TFunction<'ingredients'>,
): IngredientCategoryOption[] => {
	return Object.entries(INGREDIENT_CATEGORY_KEYS).map(
		([groupKey, itemKeys]) => ({
			group: t(`groups.${groupKey}`),
			options: itemKeys.map((itemKey) => ({
				value: itemKey,
				label: t(`labels.${itemKey}`),
			})),
		}),
	);
};
